"""add pending OTP resend fields

Revision ID: 52a3eb633f15
Revises: 276781b2d58a
Create Date: 2026-10-01 11:45:52.420936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52a3eb633f15'
down_revision: Union[str, Sequence[str], None] = '276781b2d58a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_registrations', sa.Column('last_sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('pending_registrations', sa.Column('resend_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_registrations', 'resend_count')
    op.drop_column('pending_registrations', 'last_sent_at')
    # ### end Alembic commands ###
