"""add encrypted verifier column to oauth states

Revision ID: b5abbc4c13fd
Revises: f66098e21a96
Create Date: 2026-10-05 15:17:50.734934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5abbc4c13fd'
down_revision: Union[str, Sequence[str], None] = 'f66098e21a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_states', sa.Column('encrypted_code_verifier', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_states', 'encrypted_code_verifier')
    # ### end Alembic commands ###
